# Generated by Django 5.1.2 on 2024-11-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_category_categoryname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='tittle',
            field=models.CharField(max_length=60),
        ),
    ]
